### ISSUE TITLE
secretkey change cause error in Beaker 

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cwsgiutils#228]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 352, in authdebug_view
    return view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 258, in wrapper
    response = view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python3.6/dist-packages/cornice/service.py", line 502, in wrapper
    response = view_(request)
  File "/app/schweizmobil/views/track.py", line 142, in update_track
    track = _get_track(request, 'update', check_owner=True)
  File "/app/schweizmobil/views/track.py", line 496, in _get_track
    if check_owner and request.authenticated_userid is None:
  File "/usr/local/lib/python3.6/dist-packages/pyramid/security.py", line 371, in authenticated_userid
    return policy.authenticated_userid(self)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/authentication.py", line 71, in authenticated_userid
    userid = self.unauthenticated_userid(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/authentication.py", line 1044, in unauthenticated_userid
    return request.session.get(self.userid_key)
  File "/usr/local/lib/python3.6/dist-packages/beaker/session.py", line 771, in __getattr__
    return getattr(self._session(), attr)
  File "/usr/local/lib/python3.6/dist-packages/beaker/session.py", line 767, in _session
    self.__dict__['_sess'] = session_cls(req, **params)
  File "/usr/local/lib/python3.6/dist-packages/beaker/session.py", line 629, in __init__
    raise BeakerException("Invalid signature")
beaker.exceptions.BeakerException: Invalid signature

**Comment by pvalsecc** [comment]
@ochriste, is it correct to say that what you want is to get a 401 error instead of a 500 error in that case?
