### ISSUE TITLE
Excessive logs while waiting for DB to be up

### ISSUE THREAD

**Issue by romanzoller** [camptocamp/c2cwsgiutils#296]
Observed in the canna_reporting project: When starting up the c2cwsgiutils-based api container, > 10k lines of (relatively useless) errors are logged until the database is available. This makes it difficult to see any other log output that might be relevant. Would it be possible to poll for the DB in a more controlled way and with minimal log output (1 line every few seconds) and only start gunicorn / sqlalchemy later?

Current example log output while waiting for DB to be available:

```
api_1      | 2019-02-19 13:02:42,093 ERROR c2cwsgiutils.wsgi Failed starting the application
api_1      | Traceback (most recent call last):
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
api_1      |     return fn()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 342, in unique_connection
api_1      |     return _ConnectionFairy._checkout(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 788, in _checkout
api_1      |     fairy = _ConnectionRecord.checkout(pool)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 529, in checkout
api_1      |     rec = pool._do_get()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
api_1      |     self._dec_overflow()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
api_1      |     compat.reraise(exc_type, exc_value, exc_tb)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
api_1      |     raise value
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1190, in _do_get
api_1      |     return self._create_connection()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 347, in _create_connection
api_1      |     return _ConnectionRecord(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 474, in __init__
api_1      |     self.__connect(first_connect_check=True)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 671, in __connect
api_1      |     connection = pool._invoke_creator(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
api_1      |     return dialect.connect(*cargs, **cparams)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 412, in connect
api_1      |     return self.dbapi.connect(*cargs, **cparams)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
api_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1      | psycopg2.OperationalError: could not connect to server: Connection refused
api_1      |    Is the server running on host "db" (172.21.0.4) and accepting
api_1      |    TCP/IP connections on port 5432?
api_1      |
api_1      |
api_1      | The above exception was the direct cause of the following exception:
api_1      |
api_1      | Traceback (most recent call last):
api_1      |   File "/opt/c2cwsgiutils/c2cwsgiutils/wsgi.py", line 20, in create_application
api_1      |     return get_app(configfile_, 'main', options=os.environ)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/pyramid/paster.py", line 30, in get_app
api_1      |     return loader.get_wsgi_app(name, options)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
api_1      |     global_conf=defaults)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
api_1      |     return loadobj(APP, uri, name=name, **kw)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
api_1      |     return context.create()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 715, in create
api_1      |     return self.object_type.invoke(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 235, in invoke
api_1      |     filtered = context.next_context.create()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 715, in create
api_1      |     return self.object_type.invoke(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/loadwsgi.py", line 152, in invoke
api_1      |     return fix_call(context.object, context.global_conf, **context.local_conf)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/paste/deploy/util.py", line 55, in fix_call
api_1      |     val = callable(*args, **kw)
api_1      |   File "/app/canna/__init__.py", line 38, in main
api_1      |     canna.models.init(config)
api_1      |   File "/app/canna/models.py", line 25, in init
api_1      |     Base.prepare(ro_bind, reflect=True)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/ext/automap.py", line 755, in prepare
api_1      |     autoload_replace=False
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 3908, in reflect
api_1      |     with bind.connect() as conn:
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2102, in connect
api_1      |     return self._connection_cls(self, **kwargs)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
api_1      |     if connection is not None else engine.raw_connection()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
api_1      |     self.pool.unique_connection, _connection)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
api_1      |     e, dialect, self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
api_1      |     exc_info
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
api_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
api_1      |     raise value.with_traceback(tb)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
api_1      |     return fn()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 342, in unique_connection
api_1      |     return _ConnectionFairy._checkout(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 788, in _checkout
api_1      |     fairy = _ConnectionRecord.checkout(pool)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 529, in checkout
api_1      |     rec = pool._do_get()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
api_1      |     self._dec_overflow()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
api_1      |     compat.reraise(exc_type, exc_value, exc_tb)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
api_1      |     raise value
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1190, in _do_get
api_1      |     return self._create_connection()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 347, in _create_connection
api_1      |     return _ConnectionRecord(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 474, in __init__
api_1      |     self.__connect(first_connect_check=True)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 671, in __connect
api_1      |     connection = pool._invoke_creator(self)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
api_1      |     return dialect.connect(*cargs, **cparams)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 412, in connect
api_1      |     return self.dbapi.connect(*cargs, **cparams)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
api_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1      | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
api_1      |    Is the server running on host "db" (172.21.0.4) and accepting
api_1      |    TCP/IP connections on port 5432?
api_1      |  (Background on this error at: http://sqlalche.me/e/e3q8)
api_1      | Traceback (most recent call last):
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 210, in run
api_1      |     self.sleep()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 360, in sleep
api_1      |     ready = select.select([self.PIPE[0]], [], [], 1.0)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
api_1      |     self.reap_workers()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
api_1      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
api_1      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
api_1      |
api_1      | During handling of the above exception, another exception occurred:
api_1      |
api_1      | Traceback (most recent call last):
api_1      |   File "/usr/local/bin/gunicorn", line 11, in <module>
api_1      |     sys.exit(run())
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
api_1      |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 223, in run
api_1      |     super(Application, self).run()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
api_1      |     Arbiter(self).run()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 232, in run
api_1      |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 345, in halt
api_1      |     self.stop()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 393, in stop
api_1      |     time.sleep(0.1)
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
api_1      |     self.reap_workers()
api_1      |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
api_1      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
api_1      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
api_1      | gunicorn exited with an error (1), restarting in 1s
```

**Comment by pvalsecc** [comment]
This is not the business of c2cwsgiutils. You should change your [code](https://github.com/camptocamp/canna_reporting/blob/master/api/canna/models.py#L25) like that:

```python
    while True:
        try:
            Base.prepare(ro_bind, reflect=True)
            continue
        except OperationalError:
            time.sleep(1)

```
